- name: Read conf_file_name
  stat:
   path: "../roles/make_nginx/files/test1.conf"
  register: confresult

- name: Print confresult
  debug:
    msg: "{{ confresult.stat.exists }}"

- name: Create config file if does noe exist
  copy:
    src: "../roles/make_nginx/files/default.conf"
    dest: "../roles/make_nginx/files/test1.conf"
  when: confresult.stat.exists == false