- name: Read conf_file_name
  set_fact:
  swarm_contents: "{{ lookup('file', '{{WORKSPACE}}/service_config/{{ group_names[0] }}/{{ inventory_hostname }}/list_of_services/services') | from_json }}"

- name: Add proxy to wmsapi
  block: 
    - name: Add new upstream
      blockinfile:
          marker: Add new upstream
          dest: /home/dimka/devops/teach/{{ conf_file_name }}
          insertafter: "#Last_upstream_add_here"      
          block: |2

                upstream {{ service_name}} {
                    server {{ stack_name }}_{{ service_name }}:8080 weight=1;
                }

    - name: Add new location
      blockinfile:
          marker: Last_location_add_here 
          dest: /home/dimka/devops/teach/{{ conf_file_name }}
          insertafter: "#Last_location_add_here"      
          block: |2

                    location {{ location_name }}/ {
                      proxy_pass         http://{{ service_name}}/;
                      proxy_redirect     off;
                      proxy_buffering    off; 
                    }  
    - name: Remove marker Add new upstream
      lineinfile :
        path: /home/dimka/devops/teach/{{ conf_file_name }}
        state: absent
        line: Add new upstream  

    - name: Remove marker Last_location_add_here 
      lineinfile :
        path: /home/dimka/devops/teach/{{ conf_file_name }}
        state: absent
        line: Last_location_add_here                       
  when: conf_file_name ==  "wmsapi01.dpl.wb.ru.conf" 
  
- name: Add proxy to front
  block: 
    - name: Add new upstream
      blockinfile:
          marker: Add new upstream
          dest: /home/dimka/devops/teach/{{ item }}
          insertafter: "#Last_upstream_add_here"      
          block: |2

                upstream {{ service_name}} {
                    server wmsapi01.dpl.wb.ru weight=1;
                    server wmsapi02.dpl.wb.ru weight=1;
                    server wmsapi.kol.wb.ru weight=1; 
                }
      loop:
        - wms.dl.wb.ru.conf
        - wms.dp.wb.ru.conf   
        - wms.kol.wb.ru.conf

    - name: Add new location
      blockinfile:
          marker: Last_location_add_here 
          dest: /home/dimka/devops/teach/{{ item }}
          insertafter: "#Last_location_add_here"      
          block: |2

                    location {{ location_name }}/ {
                      proxy_pass         http://{{ service_name}}{{ location_name }}/;
                      proxy_redirect     off;
                      proxy_buffering    off; 
                    }
      loop:
        - wms.dl.wb.ru.conf
        - wms.dp.wb.ru.conf   
        - wms.kol.wb.ru.conf 
    
    - name: Remove marker Add new upstream
      lineinfile :
        path: /home/dimka/devops/teach/{{ item }}
        state: absent
        line: Add new upstream 
      loop:
        - wms.dl.wb.ru.conf
        - wms.dp.wb.ru.conf   
        - wms.kol.wb.ru.conf          

    - name: Remove marker Last_location_add_here 
      lineinfile :
        path: /home/dimka/devops/teach/{{ item }}
        state: absent
        line: Last_location_add_here 
      loop:
        - wms.dl.wb.ru.conf
        - wms.dp.wb.ru.conf   
        - wms.kol.wb.ru.conf                       
  when: conf_file_name == "front"